### ISSUE TITLE
Set GitLab build status to pending before the build starts

### ISSUE THREAD

**Issue by ananace** [Argelbargel/gitlab-branch-source-plugin#15]
In case no executors are ready when a commit is pushed, to tell GitLab that a build will be happening as soon as possible.

Should prevent people from seeing things like this when the Jenkins instance is busy;
![screenshot_20170329_110316](https://cloud.githubusercontent.com/assets/534460/24446864/53294b62-146f-11e7-9a6c-c80f3612344e.png)

**Comment by Argelbargel** [comment]
TODO: implement [QueueListener#onEnterWaiting()](http://javadoc.jenkins-ci.org/hudson/model/queue/QueueListener.html#onEnterWaiting(hudson.model.Queue.WaitingItem)).

**Comment by Argelbargel** [comment]
It seems that this cannot be done (at least not easily). To update a commit's build-status gitlab requires a reference to a commit. The commit-id is determined when the actual run is started after it left the queue.

In theory i could update the build-status to pending when an event triggered via a webhook matches a source but then the plugin would behave different for manually triggered builds and differ from the way the gitlab-plugin works. As my goal is to augment the gitlab-plugin with scm-api-functionality while adhereing to it's principal mechanics i will not implement this for now.

---

Research into this revealed another bug: currently i add the meta-data used to publish the build-status to the job, not the run. This means that any manually triggered run publishes it's status to the pipeline of the last commit which triggered a SCMEvent - which might not be the commit that is built by the manually triggered run.

**Comment by Argelbargel** [comment]
@ace13: i also wonder why you're getting the message about gitlab not being able to connect to the ci-server. Right now gitlab "knows" about jenkins only insofar as it receives build-status-updates from it. The plugin does not register Jenkins as a runner or anything. So i do not know why/how it should try to connect to it.

Do get this message even before the first build-status-update is sent for the merge-request or only for changes pushed afterwards? There is an handler for requests for the build-status in the gitlab-plugins - perhaps it is called based on the url given when updating the build-status?

**Comment by ace13** [comment]
The "Failed to connect" message seems to only occur in the very rare instance where the build has received a status report from before the merge request is created, and then no messages following that point. So that it seems to GitLab like the pipeline suddenly disappeared into the ether.

---

One of the problems we have is that if the build doesn't report anything inside of a short window, then the merge request will assume that CI has already run, or maybe even that there's no CI system available. Meaning people can merge changes that have not been tested yet, which is something we can not afford to allow.

Personally, I'd be perfectly fine with this only triggering on webhooks, since that's when it's the most important - when a merge request has just been opened.
Though it's also possible we could solve this issue with our own tiny hook service that just reports back that a build is pending the moment the hook is received.

**Comment by Argelbargel** [comment]
@ace13: thought so. this must mean that gitlab remembers to url of the last update and tries to determine that state from that. as i haven't implemented the required handler yet it reports the error. i'll see if i can fix that by implementing the handler.
