### ISSUE TITLE
Allow for publishing build status updates on manually launched builds

### ISSUE THREAD

**Issue by ananace** [Argelbargel/gitlab-branch-source-plugin#23]
Currently, the only build status updates that happen seem to be due to either webhooks from the GitLab projects themselves, or when a project scan runs in Jenkins.

It would be nice if build status changes were published for builds launched by the 'Build Now' feature as well.

**Comment by Argelbargel** [comment]
I think that is because the action carrying the required data is added only when the build is triggered that way. Might also be that i actively disabled it because I only wanted the gitlab-pipeline to run when there was a commit as the build status updates get confusing when there are updates form multiple builds (just like with the gitlab-plugin). Either way, I'll look into it...

**Comment by cjbush** [comment]
I'd like to +1 this enhancement request. We occasionally need to launch builds manually (e.g. if one fails due to an unrelated issue with the build node) and it's pretty annoying that the pipeline doesn't get updated when the build passes/fails.

**Comment by dastanko** [comment]
+1

**Comment by guillaumelecerf** [comment]
+1
