### ISSUE TITLE
Build status reporting as 'result' doesn't work as intended when building multiple times

### ISSUE THREAD

**Issue by ananace** [Argelbargel/gitlab-branch-source-plugin#28]
When using build status reporting set to report 'result', then each separate Jenkins build will end up being reported as a separate job for the same pipeline to GitLab.
This means that a single failed build will always mean the entire GitLab pipeline will considered to be failed, no matter how many other builds you run for it.

![screenshot_20170705_110023](https://user-images.githubusercontent.com/534460/27857236-38cd1dd0-6171-11e7-9ed9-3a2e8f1b798c.png)

A good discussion about this can be read in the recent comments for https://gitlab.com/gitlab-org/gitlab-ce/issues/26552

**Comment by lainosantos** [comment]
Yeah. This occurs too when reporting as 'stages'.

**Comment by Argelbargel** [comment]
Jep, this is really annoying - happens with the currently released version of the gitlab-plugin to, though if i remember correctly (that's the reason we're simply ignoring the gitlab-side of the pipeline at work currently).

I'll see if i can get some clues from the comments linked by @ace13...

**Comment by cjbush** [comment]
Is there a work-around for this issue?

**Comment by cjbush** [comment]
So just for fun I modified the publishBuildStatus method to always publish "jenkins" for the context instead of "Build ###" for the name, and this appears to have worked. Reading through the discussion @ace13 linked, it appears that the Name (or context in this case) parameter to the API call needs to be identical for the step to count as a rebuild.

**Comment by Argelbargel** [comment]
@cjbush: no, but i think, i narrowed down the cause for the problem. The cause seems to be that both this plugin and the gitlab-plugin use the name/context-parameter of the [build-status-api](https://docs.gitlab.com/ce/api/commits.html#post-the-build-status-to-a-commit) to differentiate the pipeline-stage or the build that was run.

According to the comments in the [issue linked](https://gitlab.com/gitlab-org/gitlab-ce/issues/26552) by @ace13 this parameter has to stay the same for gitlab to recognize retries. That would be easy to fix but then we'd loose the display of the different stages of the jenkins-pipeline in gitlab - they would be replaced by a single "jenkins" or something like that. [*EDIT*: you found that out by yourself already :-)]

**Comment by ace13** [comment]
I can add that reporting as 'stages' works fine, at least for the ~200 projects we're now running with the branch source plugin.

But yeah, if you don't want per-stage reporting then something needs to be done, and I get the feeling that people are - in almost all cases - only going to be interested in the build that actually applies as the result for the commit, so having it overwrite the old build result probably won't be that bad for them.

**Comment by cjbush** [comment]
@Argelbargel if you want I can open a PR and let you look at the change I made. I need to clean it up a little first.

**Comment by Argelbargel** [comment]
@cjbush: that would be great. I think, we'll have to enhance that a bit to make the behaviour configurable as to not break uses like that of @ace13 but it'll be a base for that.

**Comment by ace13** [comment]
I mean, as long as the change doesn't effect build status reporting as
'stages' - which it really shouldn't need to - then my use case won't be
affected.

**Comment by Argelbargel** [comment]
Ah. Ok, that would be a reasonable solution. I've to look at the code to be sure, but i think, i use the same methods for both cases e.g. to ensure currently running stages get properly when a pipeline build fails reported but that should be easy to adjust.
