### ISSUE TITLE
Make available via plugin registry/update center

### ISSUE THREAD

**Issue by keirlawson** [Argelbargel/gitlab-branch-source-plugin#42]
It would be great if this plugin could be made available via these means, I'd like to try it out on our Jenkins but we have a policy of only installing plugins that can be updated via the update centre.

**Comment by Argelbargel** [comment]
There are plans to merge this plugin with the [gitlab-plugin](https://github.com/jenkinsci/gitlab-plugin) (see [issue #499](https://github.com/jenkinsci/gitlab-plugin/issues/499)). 

So while i understand both your wish and your company's policy, i hesitate to release this more publicly than here as this would bind more time to further maintaining/enhancing this version instead of concentrating on merging the plugins (which i do not find enough time atm, too :-/)

I'll think it over and speak with the maintainers of the gitlab-plugin about this request.
